org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.java.home=C:\\Program Files\\OpenLogic\\jdk-17.0.13.11-hotspot
android.useAndroidX=true
android.enableJetifier=false
MYAPP_RELEASE_STORE_FILE=my-app-key.keystore
MYAPP_RELEASE_KEY_ALIAS=my-app-alias
MYAPP_RELEASE_STORE_PASSWORD=123456
MYAPP_RELEASE_KEY_PASSWORD=123456
# Tắt tính năng kiểm tra đường dẫn tuyệt đối gây lỗi different roots
kotlin.incremental=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
